# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "easycrumbs"
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stanis\u{142}aw Kolarzowski"]
  s.date = "2012-04-23"
  s.description = "Easy breadcrumbs for your website"
  s.email = "stanislaw.kolarzowski@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "easycrumbs.gemspec",
    "lib/easycrumbs.rb",
    "lib/easycrumbs/breadcrumb.rb",
    "lib/easycrumbs/collection.rb",
    "lib/easycrumbs/errors.rb",
    "lib/easycrumbs/view_helpers.rb",
    "test/helper.rb",
    "test/routes.rb",
    "test/support/helpers/actors_helper.rb",
    "test/support/helpers/application_helper.rb",
    "test/support/helpers/countries_helper.rb",
    "test/support/helpers/movies_helper.rb",
    "test/support/stub_request.rb",
    "test/test_custom_collection.rb",
    "test/test_easycrumbs.rb"
  ]
  s.homepage = "http://github.com/staszek/easycrumbs"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Easy breadcrumbs"
  s.test_files = [
    "test/helper.rb",
    "test/routes.rb",
    "test/support/helpers/actors_helper.rb",
    "test/support/helpers/application_helper.rb",
    "test/support/helpers/countries_helper.rb",
    "test/support/helpers/movies_helper.rb",
    "test/support/stub_request.rb",
    "test/test_custom_collection.rb",
    "test/test_easycrumbs.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.2.0"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.12"])
      s.add_development_dependency(%q<shoulda>, ["= 2.11.3"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2.0"])
      s.add_dependency(%q<mocha>, ["= 0.9.12"])
      s.add_dependency(%q<shoulda>, ["= 2.11.3"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2.0"])
    s.add_dependency(%q<mocha>, ["= 0.9.12"])
    s.add_dependency(%q<shoulda>, ["= 2.11.3"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

